FORMAT: 1A
HOST: https://notesth.herokuapp.com/

# notesth

This document contains the API list for demonstration app for realtime services (Ably, Pusher, PubNub)

## Ably Authentication [/auth/ably]

### Get Authentication Data [GET]

When the Ably client connects to server, this api is used for `authUrl`:

```js
const client = new Ably.Realtime({
  authUrl: '/auth/ably'
})
```

+ Response 200 (application/json)

        {
            "keyName": "H0LsjC.iYqlTz",
            "timestamp": 1546268384241,
            "nonce": "7029813199355550",
            "mac": "zbV/M+iBI2p9JnyDIuGxBsvgTiNjpXiT6Gv1iJPEg+I="
        }

## Pusher Authentication [/auth/pusher]

### Get Authentication Data [POST]

When the Pusher client connects to server, this api is used for `authEndpoint`:

```js
const client = new Pusher(({
  cluster: 'ap1',
  authEndpoint: '/auth/pusher'
})
```

+ Request (application/json)

        {
            "socket_id": "7034.42624067",
            "channel_name": "private-c8138850-0d0d-11e9-bde9-29d4cefb6756"
        }

+ Response 200 (application/json)

        {
            "auth": "09z0c31hom69074d4f04:3e1c73b18478135a0d0195sdcsd1822997b90724548405669f1cc889077810de"
        }